from pathlib import Path

from src import config, mod_manager


def _dep(name: str, version: str = "1.0.0") -> dict[str, str]:
    return {"Name": name, "Version": version}


def _plan_names(mods: list[mod_manager.Mod]) -> list[str]:
    return [mod.name for mod in mods]


def _write_blacklist(mods_dir: Path, entries: list[str]) -> Path:
    blacklist_path = mods_dir / "blacklist.txt"
    blacklist_path.write_text("\n".join(entries) + "\n", encoding="utf-8")
    return blacklist_path


_EXPECTED_BLACKLIST_HEADER = (
    "# This is the blacklist. Lines starting with # are ignored.\n"
    "# Mod folders and archives listed in this file will be disabled.\n"
    "# ExampleFolder\n"
    "# SomeMod.zip\n"
    "\n"
    "# The following blacklist is generated by celeste-mod-manager.\n"
)


def _root(name: str, filename: str | None = None) -> dict[str, str]:
    return {
        "name": name,
        "version": "1.0.0",
        "filename": filename or f"{name}.zip",
    }


def test_disable_plan_includes_enabled_exclusive_dependencies(
    mods_dir: Path, mod_zip_factory, installed_mods_writer
):
    mod_zip_factory(mods_dir, "Root.zip", "Root", deps=[_dep("Alpha"), _dep("Beta")])
    mod_zip_factory(mods_dir, "Alpha.zip", "Alpha")
    mod_zip_factory(mods_dir, "Beta.zip", "Beta")
    installed_mods_writer(mods_dir, [_root("Root")])

    mods, status = mod_manager.build_disable_plan("Root")

    assert status == mod_manager.ModToggleStatus.READY
    assert _plan_names(mods) == ["Root", "Alpha", "Beta"]


def test_disable_plan_excludes_dependencies_used_by_other_enabled_mod(
    mods_dir: Path, mod_zip_factory, installed_mods_writer
):
    mod_zip_factory(mods_dir, "Root.zip", "Root", deps=[_dep("SharedDependency")])
    mod_zip_factory(
        mods_dir, "OtherRoot.zip", "OtherRoot", deps=[_dep("SharedDependency")]
    )
    mod_zip_factory(mods_dir, "SharedDependency.zip", "SharedDependency")
    installed_mods_writer(mods_dir, [_root("Root"), _root("OtherRoot")])

    mods, status = mod_manager.build_disable_plan("Root")

    assert status == mod_manager.ModToggleStatus.READY
    assert _plan_names(mods) == ["Root"]


def test_disable_plan_ignores_already_disabled_mods_when_checking_enabled_dependents(
    mods_dir: Path, mod_zip_factory, installed_mods_writer
):
    mod_zip_factory(mods_dir, "Root.zip", "Root", deps=[_dep("SharedDependency")])
    mod_zip_factory(
        mods_dir, "DisabledRoot.zip", "DisabledRoot", deps=[_dep("SharedDependency")]
    )
    mod_zip_factory(mods_dir, "SharedDependency.zip", "SharedDependency")
    installed_mods_writer(mods_dir, [_root("Root"), _root("DisabledRoot")])
    _write_blacklist(mods_dir, ["# existing comment", "DisabledRoot.zip"])

    mods, status = mod_manager.build_disable_plan("Root")

    assert status == mod_manager.ModToggleStatus.READY
    assert _plan_names(mods) == ["Root", "SharedDependency"]


def test_disable_plan_excludes_other_root_mods(
    mods_dir: Path, mod_zip_factory, installed_mods_writer
):
    mod_zip_factory(mods_dir, "Root.zip", "Root", deps=[_dep("DependencyRoot")])
    mod_zip_factory(mods_dir, "DependencyRoot.zip", "DependencyRoot")
    installed_mods_writer(mods_dir, [_root("Root"), _root("DependencyRoot")])

    mods, status = mod_manager.build_disable_plan("Root")

    assert status == mod_manager.ModToggleStatus.READY
    assert _plan_names(mods) == ["Root"]


def test_disable_plan_rejects_non_root_mod(
    mods_dir: Path, mod_zip_factory, installed_mods_writer
):
    mod_zip_factory(mods_dir, "Root.zip", "Root", deps=[_dep("Dependency")])
    mod_zip_factory(mods_dir, "Dependency.zip", "Dependency")
    installed_mods_writer(mods_dir, [_root("Root")])

    mods, status = mod_manager.build_disable_plan("Dependency")

    assert mods == []
    assert status == mod_manager.ModToggleStatus.NOT_RECORDED_ROOT


def test_enable_plan_rejects_non_root_mod(
    mods_dir: Path, mod_zip_factory, installed_mods_writer
):
    mod_zip_factory(mods_dir, "Root.zip", "Root", deps=[_dep("Dependency")])
    mod_zip_factory(mods_dir, "Dependency.zip", "Dependency")
    installed_mods_writer(mods_dir, [_root("Root")])
    _write_blacklist(mods_dir, ["Root.zip", "Dependency.zip"])

    mods, status = mod_manager.build_enable_plan("Dependency")

    assert mods == []
    assert status == mod_manager.ModToggleStatus.NOT_RECORDED_ROOT


def test_enable_plan_includes_disabled_dependencies(
    mods_dir: Path, mod_zip_factory, installed_mods_writer
):
    mod_zip_factory(mods_dir, "Root.zip", "Root", deps=[_dep("Dependency")])
    mod_zip_factory(mods_dir, "Dependency.zip", "Dependency")
    installed_mods_writer(mods_dir, [_root("Root")])
    _write_blacklist(mods_dir, ["Root.zip", "Dependency.zip"])

    mods, status = mod_manager.build_enable_plan("Root")

    assert status == mod_manager.ModToggleStatus.READY
    assert _plan_names(mods) == ["Root", "Dependency"]


def test_enable_plan_skips_optional_dependencies_by_default(
    mods_dir: Path, mod_zip_factory, installed_mods_writer
):
    mod_zip_factory(
        mods_dir,
        "Root.zip",
        "Root",
        deps=[_dep("RequiredDependency")],
        optional_deps=[_dep("OptionalDependency")],
    )
    mod_zip_factory(mods_dir, "RequiredDependency.zip", "RequiredDependency")
    mod_zip_factory(mods_dir, "OptionalDependency.zip", "OptionalDependency")
    installed_mods_writer(mods_dir, [_root("Root")])
    _write_blacklist(
        mods_dir, ["Root.zip", "RequiredDependency.zip", "OptionalDependency.zip"]
    )

    mods, status = mod_manager.build_enable_plan("Root")

    assert status == mod_manager.ModToggleStatus.READY
    assert _plan_names(mods) == ["Root", "RequiredDependency"]


def test_enable_plan_includes_optional_dependencies_when_requested(
    mods_dir: Path, mod_zip_factory, installed_mods_writer
):
    mod_zip_factory(
        mods_dir,
        "Root.zip",
        "Root",
        deps=[_dep("RequiredDependency")],
        optional_deps=[_dep("OptionalDependency")],
    )
    mod_zip_factory(mods_dir, "RequiredDependency.zip", "RequiredDependency")
    mod_zip_factory(mods_dir, "OptionalDependency.zip", "OptionalDependency")
    installed_mods_writer(mods_dir, [_root("Root")])
    _write_blacklist(
        mods_dir, ["Root.zip", "RequiredDependency.zip", "OptionalDependency.zip"]
    )

    mods, status = mod_manager.build_enable_plan("Root", optional=True)

    assert status == mod_manager.ModToggleStatus.READY
    assert _plan_names(mods) == ["Root", "RequiredDependency", "OptionalDependency"]


def test_enable_and_disable_update_blacklist_with_standard_header(
    mods_dir: Path, mod_zip_factory, installed_mods_writer
):
    mod_zip_factory(mods_dir, "Root.zip", "Root", deps=[_dep("Dependency")])
    mod_zip_factory(mods_dir, "Dependency.zip", "Dependency")
    installed_mods_writer(mods_dir, [_root("Root")])
    _write_blacklist(mods_dir, ["# old comment", "OldDisabled.zip"])

    mods_to_disable, disable_status = mod_manager.build_disable_plan("Root")
    assert disable_status == mod_manager.ModToggleStatus.READY

    assert mod_manager.disable_mods(mods_to_disable)
    assert (mods_dir / "blacklist.txt").read_text(encoding="utf-8") == (
        _EXPECTED_BLACKLIST_HEADER
        + "Dependency.zip\n"
        + "OldDisabled.zip\n"
        + "Root.zip\n"
    )

    mods_to_enable, enable_status = mod_manager.build_enable_plan("Root")
    assert enable_status == mod_manager.ModToggleStatus.READY

    assert mod_manager.enable_mods(mods_to_enable)
    assert (mods_dir / "blacklist.txt").read_text(encoding="utf-8") == (
        _EXPECTED_BLACKLIST_HEADER + "OldDisabled.zip\n"
    )


def test_uninstall_removes_mods_from_blacklist(
    mods_dir: Path, mod_zip_factory, installed_mods_writer
):
    mod_zip_factory(mods_dir, "Root.zip", "Root", deps=[_dep("Dependency")])
    mod_zip_factory(mods_dir, "Dependency.zip", "Dependency")
    installed_mods_writer(mods_dir, [_root("Root")])
    _write_blacklist(
        mods_dir,
        [
            "Root.zip",
            "Dependency.zip",
            "OtherDisabled.zip",
        ],
    )
    mods_to_uninstall, status = mod_manager.build_uninstall_plan("Root")
    assert status == mod_manager.UninstallModStatus.READY

    assert mod_manager.uninstall_mods(mods_to_uninstall)

    assert (mods_dir / "blacklist.txt").read_text(encoding="utf-8") == (
        _EXPECTED_BLACKLIST_HEADER + "OtherDisabled.zip\n"
    )


def test_uninstall_mods_ignores_root_record_when_root_tracking_disabled(
    mods_dir: Path, mod_zip_factory, monkeypatch
):
    monkeypatch.setattr(config, "_ENABLE_ROOT_INSTALL_TRACK", False)
    mod_zip_factory(mods_dir, "Root.zip", "Root")
    (mods_dir / "installed_mods.yml").write_text("not: [valid\n", encoding="utf-8")
    _write_blacklist(mods_dir, ["Root.zip", "OtherDisabled.zip"])
    mod = next(mod for mod in mod_manager.get_installed_mods() if mod.name == "Root")

    assert mod_manager.uninstall_mods([mod])
    assert (mods_dir / "blacklist.txt").read_text(encoding="utf-8") == (
        _EXPECTED_BLACKLIST_HEADER + "OtherDisabled.zip\n"
    )


def test_root_tracking_commands_report_disabled_when_root_tracking_disabled(
    mods_dir: Path, mod_zip_factory, monkeypatch
):
    monkeypatch.setattr(config, "_ENABLE_ROOT_INSTALL_TRACK", False)
    mod_zip_factory(mods_dir, "Root.zip", "Root")

    disable_mods, disable_status = mod_manager.build_disable_plan("Root")
    enable_mods, enable_status = mod_manager.build_enable_plan("Root")
    uninstall_mods, uninstall_status = mod_manager.build_uninstall_plan("Root")

    assert disable_mods == []
    assert disable_status == mod_manager.ModToggleStatus.ROOT_TRACK_DISABLED
    assert enable_mods == []
    assert enable_status == mod_manager.ModToggleStatus.ROOT_TRACK_DISABLED
    assert uninstall_mods == []
    assert uninstall_status == mod_manager.UninstallModStatus.ROOT_TRACK_DISABLED


def test_build_plans_report_missing_and_unchanged_states(
    mods_dir: Path, mod_zip_factory, installed_mods_writer
):
    mod_zip_factory(mods_dir, "Root.zip", "Root")
    installed_mods_writer(mods_dir, [_root("Root")])

    _, missing_status = mod_manager.build_disable_plan("Missing")
    _, enabled_status = mod_manager.build_enable_plan("Root")

    _write_blacklist(mods_dir, ["Root.zip"])
    _, disabled_status = mod_manager.build_disable_plan("Root")

    assert missing_status == mod_manager.ModToggleStatus.NOT_INSTALLED
    assert enabled_status == mod_manager.ModToggleStatus.ALREADY_ENABLED
    assert disabled_status == mod_manager.ModToggleStatus.ALREADY_DISABLED
