from pathlib import Path
from types import SimpleNamespace

from src import config, mod_manager
from src.cli import CelesteModCLI


_EXPECTED_BLACKLIST_HEADER = (
    "# This is the blacklist. Lines starting with # are ignored.\n"
    "# Mod folders and archives listed in this file will be disabled.\n"
    "# ExampleFolder\n"
    "# SomeMod.zip\n"
    "\n"
    "# The following blacklist is generated by celeste-mod-manager.\n"
)
_EXPECTED_MOD_OPTIONS_ORDER_HEADER = (
    "# This is the Mod Options order file. Lines starting with # are ignored.\n"
    "# Mod folders and archives in this file will be displayed in the same order in the Mod Options menu.\n"
    '# To define the position of the "Everest Core" options, put "Everest" on a line.\n'
    "# ExampleFolder\n"
    "# SomeMod.zip\n"
    "\n"
    "# The following mod options order is generated by celeste-mod-manager.\n"
)


def _dep(name: str, version: str = "1.0.0") -> dict[str, str]:
    return {"Name": name, "Version": version}


def _mod_info(name: str, version: str = "1.0.0"):
    return SimpleNamespace(
        name=name,
        version=version,
        submissionFile=SimpleNamespace(
            url=f"https://example.invalid/{name}.zip",
            size=100,
        ),
    )


def test_parse_required_mods_file_ignores_empty_lines_and_line_comments(
    tmp_path: Path,
):
    requirement_path = tmp_path / "required_mods.txt"
    requirement_path.write_text(
        "\n"
        "# comment\n"
        "  StrawberryJam2021  \n"
        "Another Mod\n",
        encoding="utf-8",
    )

    assert mod_manager.parse_required_mods_file(str(requirement_path)) == [
        "StrawberryJam2021",
        "Another Mod",
    ]


def test_apply_existing_mods_rewrites_blacklist_without_root_metadata(
    mods_dir: Path, mod_zip_factory
):
    mod_zip_factory(mods_dir, "Root.zip", "Root", deps=[_dep("Dependency")])
    mod_zip_factory(mods_dir, "Dependency.zip", "Dependency")
    mod_zip_factory(mods_dir, "Other.zip", "Other")
    (mods_dir / "blacklist.txt").write_text(
        "OldManualEntry.zip\nRoot.zip\n", encoding="utf-8"
    )

    plan = mod_manager.build_apply_plan(["Root"])

    assert plan.status == mod_manager.ApplyPlanStatus.READY
    assert [mod.name for mod in plan.already_available] == ["Root"]
    assert [mod.name for mod in plan.enabled_closure] == ["Dependency", "Root"]
    assert [mod.name for mod in plan.blacklisted] == ["Other"]

    assert mod_manager.apply_required_mods(plan)
    assert (mods_dir / "blacklist.txt").read_text(encoding="utf-8") == (
        _EXPECTED_BLACKLIST_HEADER + "Other.zip\n"
    )
    assert (mods_dir / "modoptionsorder.txt").read_text(encoding="utf-8") == (
        _EXPECTED_MOD_OPTIONS_ORDER_HEADER + "Root.zip\n"
    )
    assert not (mods_dir / "installed_mods.yml").exists()


def test_ensure_mod_root_false_does_not_record_existing_mod(
    mods_dir: Path, mod_zip_factory
):
    mod_zip_factory(mods_dir, "Root.zip", "Root")

    mod, status = mod_manager.ensure_mod("Root", root=False)

    assert status == mod_manager.EnsureModStatus.ALREADY_EXISTS
    assert mod is not None
    assert not (mods_dir / "installed_mods.yml").exists()


def test_apply_downloads_missing_root_and_dependency(
    mods_dir: Path, mod_zip_factory, monkeypatch
):
    def fake_get_mod_info(mod_name: str):
        if mod_name in {"Root", "Dependency"}:
            return _mod_info(mod_name)
        return None

    def fake_download_mod(mod_info):
        deps = [_dep("Dependency")] if mod_info.name == "Root" else None
        mod_zip_factory(
            mods_dir,
            f"{mod_info.name}-1.0.0.zip",
            mod_info.name,
            deps=deps,
        )
        return mod_manager.Mod.from_filename(f"{mod_info.name}-1.0.0.zip")

    monkeypatch.setattr(mod_manager, "get_mod_info", fake_get_mod_info)
    monkeypatch.setattr(mod_manager, "_download_mod", fake_download_mod)

    plan = mod_manager.build_apply_plan(["Root"])

    assert plan.status == mod_manager.ApplyPlanStatus.READY
    assert [mod.name for mod in plan.downloaded] == ["Dependency", "Root"]
    assert [mod.name for mod in plan.enabled_closure] == ["Dependency", "Root"]
    assert not (mods_dir / "installed_mods.yml").exists()


def test_apply_skips_optional_dependencies_by_default(
    mods_dir: Path, mod_zip_factory
):
    mod_zip_factory(
        mods_dir,
        "Root.zip",
        "Root",
        deps=[_dep("RequiredDependency")],
        optional_deps=[_dep("OptionalDependency")],
    )
    mod_zip_factory(mods_dir, "RequiredDependency.zip", "RequiredDependency")
    mod_zip_factory(mods_dir, "OptionalDependency.zip", "OptionalDependency")

    plan = mod_manager.build_apply_plan(["Root"])

    assert plan.status == mod_manager.ApplyPlanStatus.READY
    assert [mod.name for mod in plan.enabled_closure] == ["RequiredDependency", "Root"]
    assert [mod.name for mod in plan.blacklisted] == ["OptionalDependency"]


def test_apply_includes_optional_dependencies_when_requested(
    mods_dir: Path, mod_zip_factory
):
    mod_zip_factory(
        mods_dir,
        "Root.zip",
        "Root",
        deps=[_dep("RequiredDependency")],
        optional_deps=[_dep("OptionalDependency")],
    )
    mod_zip_factory(mods_dir, "RequiredDependency.zip", "RequiredDependency")
    mod_zip_factory(mods_dir, "OptionalDependency.zip", "OptionalDependency")

    plan = mod_manager.build_apply_plan(["Root"], optional=True)

    assert plan.status == mod_manager.ApplyPlanStatus.READY
    assert [mod.name for mod in plan.enabled_closure] == [
        "OptionalDependency",
        "RequiredDependency",
        "Root",
    ]
    assert plan.blacklisted == []


def test_apply_reports_duplicate_local_mod_names(mods_dir: Path, mod_zip_factory):
    mod_zip_factory(mods_dir, "Root-a.zip", "Root")
    mod_zip_factory(mods_dir, "Root-b.zip", "Root")

    plan = mod_manager.build_apply_plan(["Root"])

    assert plan.status == mod_manager.ApplyPlanStatus.DUPLICATE_LOCAL_MOD
    assert plan.failed == ["Root"]


def test_apply_mod_options_order_follows_declared_order_with_everest(
    mods_dir: Path, mod_zip_factory
):
    mod_zip_factory(mods_dir, "Root.zip", "Root")
    mod_zip_factory(mods_dir, "Other-custom.zip", "Other")

    plan = mod_manager.build_apply_plan(["Root", "Everest", "Other"])

    assert plan.status == mod_manager.ApplyPlanStatus.READY
    assert plan.mod_options_order == ["Root.zip", "Everest", "Other-custom.zip"]


def test_apply_everest_placeholder_does_not_resolve_as_mod(
    mods_dir: Path, monkeypatch
):
    def fail_if_called(*args, **kwargs):
        raise AssertionError("Everest should not be resolved as a mod")

    monkeypatch.setattr(mod_manager, "get_mod_info", fail_if_called)
    monkeypatch.setattr(mod_manager, "_download_mod", fail_if_called)

    plan = mod_manager.build_apply_plan(["Everest"])

    assert plan.status == mod_manager.ApplyPlanStatus.READY
    assert plan.mod_options_order == ["Everest"]
    assert plan.enabled_closure == []
    assert plan.blacklisted == []


def test_apply_mod_options_order_deduplicates_declared_entries(
    mods_dir: Path, mod_zip_factory
):
    mod_zip_factory(mods_dir, "Root.zip", "Root")

    plan = mod_manager.build_apply_plan(["Root", "Everest", "Root", "Everest"])

    assert plan.status == mod_manager.ApplyPlanStatus.READY
    assert plan.mod_options_order == ["Root.zip", "Everest"]


def test_apply_dry_run_does_not_download_or_write_blacklist(
    mods_dir: Path, mod_zip_factory, monkeypatch
):
    mod_zip_factory(mods_dir, "Other.zip", "Other")
    (mods_dir / "blacklist.txt").write_text("Old.zip\n", encoding="utf-8")
    (mods_dir / "modoptionsorder.txt").write_text("OldOrder.zip\n", encoding="utf-8")
    requirement_path = mods_dir / "req.txt"
    requirement_path.write_text("Root\n", encoding="utf-8")

    monkeypatch.setattr(mod_manager, "get_mod_info", lambda mod_name: _mod_info(mod_name))

    def fail_if_downloaded(*args, **kwargs):
        raise AssertionError("dry-run should not download")

    monkeypatch.setattr(mod_manager, "_download_mod", fail_if_downloaded)

    exit_code = CelesteModCLI().apply(["--dry-run", "-r", str(requirement_path)])

    assert exit_code == 0
    assert (mods_dir / "blacklist.txt").read_text(encoding="utf-8") == "Old.zip\n"
    assert (
        (mods_dir / "modoptionsorder.txt").read_text(encoding="utf-8")
        == "OldOrder.zip\n"
    )


def test_apply_cli_requirement_file_rewrites_blacklist(
    mods_dir: Path, mod_zip_factory, capsys
):
    mod_zip_factory(mods_dir, "Root.zip", "Root")
    mod_zip_factory(mods_dir, "Other.zip", "Other")
    requirement_path = mods_dir / "req.txt"
    requirement_path.write_text("Root\n", encoding="utf-8")

    exit_code = CelesteModCLI().apply(["-r", str(requirement_path)])

    assert exit_code == 0
    assert "Requested mods: 1\n" in capsys.readouterr().out
    assert (mods_dir / "blacklist.txt").read_text(encoding="utf-8") == (
        _EXPECTED_BLACKLIST_HEADER + "Other.zip\n"
    )
    assert (mods_dir / "modoptionsorder.txt").read_text(encoding="utf-8") == (
        _EXPECTED_MOD_OPTIONS_ORDER_HEADER + "Root.zip\n"
    )


def test_apply_cli_optional_deps_includes_optional_dependencies(
    mods_dir: Path, mod_zip_factory
):
    mod_zip_factory(
        mods_dir,
        "Root.zip",
        "Root",
        optional_deps=[_dep("OptionalDependency")],
    )
    mod_zip_factory(mods_dir, "OptionalDependency.zip", "OptionalDependency")
    requirement_path = mods_dir / "req.txt"
    requirement_path.write_text("Root\n", encoding="utf-8")

    exit_code = CelesteModCLI().apply(
        ["--optional-deps", "-r", str(requirement_path)]
    )

    assert exit_code == 0
    assert (mods_dir / "blacklist.txt").read_text(encoding="utf-8") == (
        _EXPECTED_BLACKLIST_HEADER
    )


def test_apply_cli_writes_mod_options_order_with_everest_placeholder(
    mods_dir: Path, mod_zip_factory
):
    mod_zip_factory(mods_dir, "Root.zip", "Root")
    mod_zip_factory(mods_dir, "Other.zip", "Other")
    (mods_dir / "modoptionsorder.txt").write_text("Old.zip\n", encoding="utf-8")
    requirement_path = mods_dir / "req.txt"
    requirement_path.write_text("Root\nEverest\nOther\n", encoding="utf-8")

    exit_code = CelesteModCLI().apply(["-r", str(requirement_path)])

    assert exit_code == 0
    assert (mods_dir / "modoptionsorder.txt").read_text(encoding="utf-8") == (
        _EXPECTED_MOD_OPTIONS_ORDER_HEADER + "Root.zip\nEverest\nOther.zip\n"
    )


def test_apply_cli_returns_error_when_experimental_apply_is_disabled(
    mods_dir: Path, monkeypatch, capsys
):
    requirement_path = mods_dir / "req.txt"
    requirement_path.write_text("Root\n", encoding="utf-8")
    monkeypatch.setattr(config, "_ENABLE_EXPERIMENTAL_APPLY", False)

    exit_code = CelesteModCLI().apply(["-r", str(requirement_path)])

    captured = capsys.readouterr()
    assert exit_code == 1
    assert "experimental apply feature is not enabled" in captured.err
    assert not (mods_dir / "blacklist.txt").exists()


def test_apply_cli_uses_default_required_mods_path(mods_dir: Path, mod_zip_factory):
    mod_zip_factory(mods_dir, "Root.zip", "Root")
    (mods_dir / "required_mods.txt").write_text("Root\n", encoding="utf-8")

    assert CelesteModCLI().apply([]) == 0


def test_apply_cli_empty_requirement_file_returns_error(mods_dir: Path):
    requirement_path = mods_dir / "required_mods.txt"
    requirement_path.write_text("# only comments\n\n", encoding="utf-8")

    assert CelesteModCLI().apply([]) == 1
